
                        ┌───────────┐
                        │  Object   │
                        └───────────┘
                              ▲
                              │
                        ┌───────────┐
                        │ Throwable │
                        └───────────┘
                              ▲
                    ┌─────────┴─────────┐
                    │                   │
                ┌───────────┐       ┌───────────┐
                │   Error   │       │ Exception │
                └───────────┘       └───────────┘
                    ▲                   ▲
            ┌───────┘              ┌────┴──────────┐
            │                      │               │
    ┌─────────────────┐    ┌─────────────────┐┌───────────┐
    │OutOfMemoryError │... │RuntimeException ││IOException│...
    └─────────────────┘    └─────────────────┘└───────────┘
                                    ▲
                        ┌───────────┴─────────────┐
                        │                         │
            ┌─────────────────────┐ ┌─────────────────────────┐
            │NullPointerException │ │IllegalArgumentException │...
            └─────────────────────┘ └─────────────────────────┘


从继承关系可知：Throwable是异常体系的根，它继承自Object。  
Throwable有两个体系：Error和Exception，Error表示严重的错误，程序对此一般无能为力。

# 捕获异常
使用 try...catch捕获异常
```java
public class Main {
    public static void main(String[] args) {
        try {
            Point p1 = new Point(1,2);
        }catch (IllegalArgumentException e){
            System.out.println("except");
            e.printStackTrace();
        }

    }
}

record Point(int x, int y){
    //通过构造函数添加参数校验
    Point{
        if (x < y) {
            throw new IllegalArgumentException("参数错误");
        }
    }
};
```

如果不想捕获，也可以继续向上抛出异常，交给上层处理，main 函数抛出的异常会导致程序中断。
```java
class Unit {
    static void test() throws IllegalArgumentException {
        int val = div(1,0);
        System.out.println(val);
    }

    static int div(int x, int y) {
        if (y == 0) {
            throw new IllegalArgumentException("y 不能为 0");
        }
        return x / y;
    }

}
```

# 多catch语句
- 多个catch语句只有一个能被执行。
- catch的顺序非常重要：子类必须写在前面。
```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    }
}
```

# finally
- finally语句不是必须的，可写可不写；
- finally总是最后执行。

如果没有发生异常，就正常执行try { ... }语句块，然后执行finally。  
如果发生了异常，就中断执行try { ... }语句块，然后跳转执行匹配的catch语句块，最后执行finally

```java
class Unit {
    static void test() throws Exception {
        Exception origin = null;
        try {
            int val = div(1,0);
            System.out.println(val);
        }catch (IllegalArgumentException e) {
            origin = e;
            throw e;
        }finally {
            //包裹异常抛出去
            Exception e = new RuntimeException();
            if (origin != null) {
                e.addSuppressed(origin);
            }
            throw e;
        }
    }

    static int div(int x, int y) {
        if (y == 0) {
            throw new IllegalArgumentException("y 不能为 0");
        }
        return x / y;
    }
}
```

# 自定义异常
- 抛出异常时，尽量复用JDK已定义的异常类型；
- 自定义异常体系时，推荐从RuntimeException派生“根异常”，再派生出业务异常；
- 自定义异常时，应该提供多种构造方法。

```java
public class BaseException extends RuntimeException{
    BaseException(){
        super();
    }

    BaseException(String message) {
        super(message);
    }

    BaseException(Throwable cause) {
        super(cause);
    }

    BaseException(String message, Throwable cause) {
        super(message, cause);
    }
}


class OrderException extends BaseException {
    OrderException(){
        super();
    }

    OrderException(String message) {
        super(message);
    }

    OrderException(Throwable cause) {
        super(cause);
    }

    OrderException(String message, Throwable cause) {
        super(message, cause);
    }
}
```


# 系统日志
```
Logger log = Logger.getLogger("kang");
log.info("info");
log.warning("warning");
log.severe("severe");
```

# Commons Logging
Commons Logging是一个第三方日志库.  
Commons Logging的特色是，它可以挂接不同的日志系统，并通过配置文件指定挂接的日志系统。默认情况下，Commons Loggin自动搜索并使用Log4j（Log4j是另一个流行的日志系统），如果没有找到Log4j，再使用JDK Logging。









